

import click
from math import sqrt
from itertools import count

@click.command('45')
@click.option('--verbose', '-v', count=True)
@click.option('--count', '-c', type=int, default=3)
def problem_045(verbose, count):
    """Triangular, pentagonal, and hexagonal.

    Triangle, pentagonal, and hexagonal numbers are generated by the following
    formulae:
    
    Triangle |  | T_n_=_n_(_n_+1)/2 |  | 1, 3, 6, 10, 15, ...  
    ---|---|---|---|---  
    Pentagonal |  | P_n_=_n_(3_n_−1)/2 |  | 1, 5, 12, 22, 35, ...  
    Hexagonal |  | H_n_=_n_(2_n_−1) |  | 1, 6, 15, 28, 45, ...  
      
    It can be verified that T285 = P165 = H143 = 40755.
    
    Find the next triangle number that is also pentagonal and hexagonal.
    
    """

    hexes = generate_hexagonal(1)
    pents = (h for h in hexes if is_pentagonal(h))
    tris = (p for p in pents if is_triangular(p))

    for i in range(count):
        click.echo(next(tris))


def generate_hexagonal(start):
    for i in count(start):
        yield hexagonal(i)


def hexagonal(n):
    return n * (2 * n - 1)


def is_pentagonal(p):
    # Via quadratic:
    n = (1 + sqrt(1 + 24 * p )) / 6
    return int(n) == n


def is_triangular(t):
    n = (sqrt(1 + 8 * t) - 1) / 2
    return int(n) == n