
import click

from itertools import islice


@click.command('2')
@click.option('--modulo', '-m', type=int, default=2,
              help='Sum Fibonacci numbers that are multiple of this value')
@click.option('--limit', '-l', type=int, default=4000000,
              help='Sum Fibonacci numbers up to this value')
def problem_002(modulo, limit):
    """Even Fibonacci numbers

    https://projecteuler.net/problem=2

    Each new term in the Fibonacci sequence is generated by adding the 
    previous two terms. By starting with 1 and 2, the first 10 terms will be:

    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

    By considering the terms in the Fibonacci sequence whose values do not
    exceed four million, find the sum of the even-valued terms.
    """

    all_numbers = fibonacci_less_than_n(limit)
    filtered = (n for n in all_numbers if n % modulo == 0)
    total = sum(filtered)
    click.echo(total)


def fibonacci_less_than_n(n):
    for value in generate_fibonacci():
        if value > n:
            return
        else:
            yield value

def generate_fibonacci():
    yield 1
    yield 2

    previous = 1
    current = 2

    while True:
        next_value = previous + current
        previous = current
        current = next_value
        yield current