
import click

from itertools import product

@click.command('29')
@click.option('--a-limit', '-a', type=int, default=100)
@click.option('--b-limit', '-b', type=int, default=100)
def problem_029(a_limit, b_limit):
    """Distinct powers

    Consider all integer combinations of _a__b_ for 2 ≤ _a_ ≤ 5 and 2 ≤ _b_ ≤
    5:
    
    > 22=4, 23=8, 24=16, 25=32  
    >  32=9, 33=27, 34=81, 35=243  
    >  42=16, 43=64, 44=256, 45=1024  
    >  52=25, 53=125, 54=625, 55=3125  
    >
    
    If they are then placed in numerical order, with any repeats removed, we
    get the following sequence of 15 distinct terms:
    
    4, 8, 9, 16, 25, 27, 32, 64, 81, 125, 243, 256, 625, 1024, 3125
    
    How many distinct terms are in the sequence generated by _a__b_ for 2 ≤
    _a_ ≤ 100 and 2 ≤ _b_ ≤ 100?
    
    """

    pairs = product(range(2, a_limit + 1), range(2, b_limit + 1))
    powers = {a**b for a, b in pairs}
    click.echo(len(powers))